# Example Configuration with Content Correction Enabled
# ======================================================

# Processing settings
processing:
  min_segment_duration: 0.5
  max_segment_duration: 30.0
  max_workers: 4
  tts_workers: 3
  parallel_tts: true

# Filler word detection (EXPANDED)
fillers:
  mode: "rule-based"
  words:
    # Basic fillers
    - "uh"
    - "um"
    - "ah"
    # Common verbal crutches
    - "like"
    - "you know"
    - "ok"
    - "okay"
    - "so"
    - "well"
    - "right"
    # Hedge phrases
    - "i mean"
    - "you see"
    - "actually"
    - "basically"
    - "literally"
    - "sort of"
    - "kind of"

# Content correction with LLM (NEW FEATURE)
content_correction:
  enabled: true  # Set to false to disable
  mode: "openai"  # Options: 'openai', 'anthropic'
  model: "gpt-4o-mini"  # Cost-effective model
  # api_key: "sk-..."  # Optional - can use OPENAI_API_KEY env var instead
  max_tokens: 500
  temperature: 0.3

  # Correction features (enable/disable as needed)
  fix_grammar: true
  rephrase_awkward: true
  remove_repetitions: true
  improve_clarity: true

# Transcription settings
transcription:
  backend: "whisperx"
  model: "large-v2"
  language: "auto"
  device: "mps"  # Options: cuda, mps, cpu
  compute_type: "float16"

# TTS settings
tts:
  backend: "chatterbox"
  voice_mode: "custom"  # Options: default, custom, auto
  voice_reference: "voices/sample_voice_yt.wav"
  sample_rate: 44100
  normalize: true
  device: "mps"

# Video processing
video:
  sync_mode: "retime"
  quality: "high"
  codec: "h264"
  bitrate: "5M"
  gpu_acceleration: true
  hwaccel: "auto"

  transitions:
    enabled: true
    type: "crossfade"
    duration: 0.3

# Output settings
output:
  temp_dir: "temp_segments"
  keep_intermediates: false

  subtitles:
    enabled: true
    burn_in: false
    font_size: 24
    font_color: "white"
    outline_color: "black"
    position: "bottom"

  chapters:
    enabled: false
    strategy: "auto"
    min_chapter_duration: 60.0
    max_chapters: 20

# Logging
logging:
  level: "INFO"
  file: "video_processing.log"
  console: true
